nohup: ignoring input
[31-Jul-25 07:02:14 - INFO] - AnonXMusic.core.mongo - Connecting to your Mongo Database...
[31-Jul-25 07:02:14 - INFO] - AnonXMusic.core.mongo - Connected to your Mongo Database.
[31-Jul-25 07:02:14 - INFO] - AnonXMusic.core.dir - Directories Updated.
[31-Jul-25 07:02:14 - INFO] - AnonXMusic.core.git - Git Client Found [VPS DEPLOYER]
[31-Jul-25 07:02:14 - INFO] - AnonXMusic.misc - Local Database Initialized.
[31-Jul-25 07:02:14 - INFO] - AnonXMusic.core.bot - Starting Bot...
[31-Jul-25 07:02:16 - INFO] - AnonXMusic.misc - Sudoers Loaded.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/Make/AnonXMusic/__main__.py", line 63, in <module>
    asyncio.get_event_loop().run_until_complete(init())
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/workspace/Make/AnonXMusic/__main__.py", line 36, in init
    await app.start()
  File "/workspace/Make/AnonXMusic/core/bot.py", line 23, in start
    await super().start()
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/methods/utilities/start.py", line 62, in start
    await self.authorize()
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/client.py", line 333, in authorize
    return await self.sign_in_bot(self.bot_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/methods/auth/sign_in_bot.py", line 51, in sign_in_bot
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
    ...<5 lines>...
      is_signed=is_signed)
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 3065 seconds is required (caused by "auth.ImportBotAuthorization")
